name: Deploy to QA

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-1'

jobs:
  deploy-to-qa:
    if: false
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build shared library
        shell: bash
        working-directory: frontend/shared
        run: |
          npm ci
          npm run build
      - name: Transform configs
        shell: bash
        working-directory: scripts/transform-json
        env:
          API_BASE: ${{ secrets.API_BASE }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
        run: |
          go run main.go \
            --mapfile ../../frontend/public/transform_map.json \
            --configfile ../../frontend/public/public/config.json
      - name: NPM install/build
        shell: bash
        working-directory: frontend/public
        run: |
          npm ci
          CI= npm run build
      - name: Clean deploy directory
        run: |
          aws s3 rm --recursive s3://guardianforge-qa-site/app/
      - name: Copy to S3
        working-directory: frontend/public
        run: |
          aws s3 sync build s3://guardianforge-qa-site/app --no-progress --acl public-read
      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Write default params.json file
        shell: bash
        working-directory: backend/stack
        run: |
          echo "${{ secrets.PARAMS_JSON_ENCODED }}" >> params.encoded
          base64 -d -i params.encoded >> params.json
          cat params.json
      # - name: Transform configs
      #   shell: bash
      #   working-directory: scripts/transform-json
      #   env:
      #     API_BASE: ${{ secrets.API_BASE }}
      #     LOGIN_URL: ${{ secrets.LOGIN_URL }}
      #     OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      #     BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
      #   run: |
      #     go run main.go \
      #       --mapfile ../../backend/stack/transform_map.json \
      #       --configfile ../../backend/stack/params.json

      # - name: Transform params
      # - name: Build & deploy


